### ISSUE TITLE
Final Capstone

### ISSUE THREAD

**Issue by Alusp** [Alusp/book_an_appointment_back_end#15]
### Below is the screenshot
![Screenshot 1](https://user-images.githubusercontent.com/43528594/210999218-f9c17ffe-fbc8-41ce-a009-a2d9f01fadef.png)
![Screenshot 2](https://user-images.githubusercontent.com/43528594/210999222-7dcb4689-4f6d-4fb7-be68-277cf1df2857.png)
![Screenshot 3](https://user-images.githubusercontent.com/43528594/210999225-3649978d-147e-411a-849b-de14b4593bef.png)

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks are pointed✔️ 
- All tasks have been assigned✔️ 
- The point distribution is equal✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
